# -*- coding: utf-8 -*-
#"""Preparação para HTML e CSS - Desenvolvimento 1.ipynb

#Automatically generated by Colaboratory.

#Original file is located at
 #   https://colab.research.google.com/drive/1P3FL_SLFb2Vqj2wRFlcXz78nFaQWyqpT

#**Desenvolvimento 1.1**

#Declare dois arrays, cada um com um mínimo de cinco elementos, e imprima eles no terminal usando o comando print(). O primeiro array deve conter os produtos de uma loja da sua escolha (loja de comida, materiais de construção, música, etc). O segundo array deve conter os anos de nascimento de familiares e amigos seus. Lembre-se de usar nomes descritivos para nomear cada variável, e de usar o tipo de dado apropriado para cada lista (strings, booleanos, números inteiros, floats).
#"""

loja_airuma = ["Conjunto", "Calcinha", "Sutiã", "Gel de função", "Vibradores", "Brinquedos de preder"]
AnoDesigner = [1975, 1985, 1994, 2015, 2022]
print(loja_airuma)
print(AnoDesigner)

# Primeiro array - Produtos de uma loja

produtos = ["Conjunto", "Calcinha", "Sutiã", "Gel de função", "Vibradores", "Brinquedos de preder"]
for i in range(len(produtos)):
  print("Produtos da loja:", produtos[i])

# Segundo array - Anos de nascimento de familiares e amigos

AnoDesigner = [1975, 1985, 1994, 2015, 2022]
for i in range(len(AnoDesigner)):
  print(AnoDesigner[i])

#"""**Desenvovilmento 1.2**

#Copie o array apresentado embaixo no seu editor de código, e imprima no terminal: a quantidade de elementos que ele possui, o dado salvo no índice 2, o dado salvo no índice 9, e dado salvo no índice 14.

#lista_musicos = [ 'Djavan', 'Roberto Carlos', 'Elis Regina', 'Tom Jobim', 'Milton Nascimento', 'Chico Buarque', 'Nara Leão', 'Pitty', 'Simonal', 'Moacir Santos', 'Caetano Veloso', 'Elza Soares', 'Paulinho da Viola', 'Yamandú Costa', 'Gal Costa']
#"""

lista_musicos = [ 'Djavan', 'Roberto Carlos', 'Elis Regina', 'Tom Jobim', 'Milton Nascimento', 'Chico Buarque', 'Nara Leão', 'Pitty', 'Simonal', 'Moacir Santos', 'Caetano Veloso', 'Elza Soares', 'Paulinho da Viola', 'Yamandú Costa', 'Gal Costa']

print(len(lista_musicos))
print(lista_musicos[2])
print(lista_musicos[9])
print(lista_musicos[14])

#**Desenvolvimento 1.3**

# Uma nova loja de cosméticos abriu no seu bairro e pediram para você elaborar um sistema que imprime na tela na frente da loja os novos produtos que chegaram. O sistema da loja já tem um array com os produtos, você precisa apenas imprimir eles no terminal, um por um.

#Como desafio opcional, tente imprimir cada produto com a frase "Temos [produto] à venda!" (ex. "Temos máscaras faciais à venda!").

#lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'xampus', 'sabonetes', 'delineadores']

#"""

lista_produtos = ['máscaras faciais', 'batons', 'esmaltes', 'perfumes', 'loções', 'xampus', 'sabonetes', 'delineadores']
print(len(lista_produtos))
for i in range(len(lista_produtos)):
 print("Temos " + lista_produtos[i] + " à venda!")

#"""
#**Desenvolvimento 1.4**

#A loja de cosméticos ficou muito feliz com seu trabalho e chamaram você novamente! Dessa vez, eles precisam que você atualize o array de produtos. Agora, eles estão vendendo rímel ao invés de batons, e cremes hidratantes no lugar de loções. Além disso, ficaram sem delineadores, então precisam que você remova ele da lista de produtos. Imprima a nova lista no terminal para verificar que as alterações foram realizadas corretamente.

#lista_produtos = ["máscaras faciais", "batons", "esmaltes", "perfumes", "loções", "xampus", "sabonetes", "delineadores"]

#Como desafio, adicione dois novos produtos da sua escolha à lista."""

lista_produtos = ["máscaras faciais", "batons", "esmaltes", "perfumes", "loções", "xampus", "sabonetes", "delineadores"]
lista_produtos[1] = "Rímel"
lista_produtos[4] = "cremes hidratantes"
lista_produtos.pop()
print(lista_produtos)


# Desafio: adicionar dois novos produtos
lista_produtos.append("base de pele")
lista_produtos.append("condicionadores")
for i in range(len(lista_produtos)):
  print("Temos", lista_produtos[i], "à venda")